apiVersion: v1
data:
  config.json: |-
    {
      "listener": {
        "tcp":{
          "address": "0.0.0.0:8200",
          "tls_disable": 1,
          "tls_cert_file": "/etc/tls/vault.pem",
          "tls_key_file": "/etc/tls/vault-key.pem"
        }
      },
      "storage": {
        "consul": {
          "address": "consul:8500",
          "path": "vault/",
          "disable_registration": "true",
          "ha_enabled": "true"
        }
      },
      "ui": true
    }
kind: ConfigMap
  name: vault
  namespace: hashcorp
